
package view.payment;

import controller.global.Controller_Print_JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utility.initializer.Initializer;

/**
 *
 * @author Jordan
 */
public class Dialog_Assessed extends javax.swing.JDialog implements Initializer{

    private final Panel_Payment view;
    
    public Dialog_Assessed(java.awt.Frame parent, boolean modal, Panel_Payment view) {
        super(parent, modal);
        initComponents();
        this.view = view;
        
        initDaoImpl();
        initJCompModelLoaders();
        initControllers();
        initViewComponents();
    }

    @Override
    public void initGridBagConstraints() {
    }
    
    @Override
    public void initJCompModelLoaders() {
    }

    @Override
    public void initRenderers() {
    }

    @Override
    public void initModels() {
    }

    @Override
    public void initViewComponents() {
        if(view.getJcmbModeOfPayment().getSelectedItem().toString().trim().equalsIgnoreCase("Installment")){
            String payTerm = view.getJcmbPaymentTerm().getSelectedItem().toString().trim();
            jlblPaymentTerm.setText(payTerm);
            JTable t =  view.getJtblBalanceBreakDown();
            DefaultTableModel tableModel = (DefaultTableModel) jtblAssessed.getModel();
            for(int row = 0; row < t.getRowCount(); row++){
                Object feeName = t.getValueAt(row,0);
                Object feeAmount = t.getValueAt(row,1);
                Object dueDate = t.getValueAt(row,3);
                Object category = t.getValueAt(row,5);
                tableModel.addRow(new Object[]{feeName,feeAmount,dueDate.toString().contains("1970")? "":dueDate,category});
            }
            jtblAssessed.setModel(tableModel);
            String lastName = view.getJtfLastName().getText().trim();
            String firstName = view.getJtfFirstName().getText().trim();
            String middleName = view.getJtfMiddleName().getText().trim();
            jlblStudentName.setText(lastName+", "+firstName+" "+middleName);
        }
    }

    @Override
    public void initControllers() {
        jbtnPrint.addActionListener(new Controller_Print_JButton(jpnlPrintPanel, 1));
    }

    @Override
    public void initDaoImpl() {
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jpnlPrintPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAssessed = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlblPaymentTerm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblStudentName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jpnlPrintPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnlPrintPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        jpnlPrintPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        jpnlPrintPanel.setLayout(new java.awt.GridBagLayout());

        jtblAssessed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtblAssessed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fee ", "Amount ", "Due Date", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblAssessed.setShowHorizontalLines(false);
        jtblAssessed.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jtblAssessed);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlPrintPanel.add(jScrollPane1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Payment Term :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel2, gridBagConstraints);

        jlblPaymentTerm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblPaymentTerm.setText("PayTerm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jlblPaymentTerm, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Student Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel3, gridBagConstraints);

        jlblStudentName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblStudentName.setText("stdName");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jlblStudentName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlPrintPanel.add(jPanel2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Assessment ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpnlPrintPanel.add(jLabel1, gridBagConstraints);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpnlPrintPanel.add(jPanel3, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jpnlPrintPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jPanel4, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jbtnPrint.setText("Print");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jbtnPrint, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JLabel jlblPaymentTerm;
    private javax.swing.JLabel jlblStudentName;
    private javax.swing.JPanel jpnlPrintPanel;
    private javax.swing.JTable jtblAssessed;
    // End of variables declaration//GEN-END:variables
}
