package view.grades;




public class View_Dialog_Inputgrade_LongMethod extends javax.swing.JDialog {


    public View_Dialog_Inputgrade_LongMethod(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_toppanel = new javax.swing.JPanel();
        panel_advisoryselection = new javax.swing.JPanel();
        btn_Edit = new javax.swing.JButton();
        lbl_section = new javax.swing.JLabel();
        combo_section = new javax.swing.JComboBox<>();
        lbl_gradelevel = new javax.swing.JLabel();
        combo_gradelevel = new javax.swing.JComboBox<>();
        lbl_subcode = new javax.swing.JLabel();
        combo_subcode = new javax.swing.JComboBox<>();
        lbl_subjectname = new javax.swing.JLabel();
        combo_subjectname = new javax.swing.JComboBox<>();
        lbl_gradingperiod = new javax.swing.JLabel();
        combo_gradingperiod = new javax.swing.JComboBox<>();
        btn_addrow = new javax.swing.JButton();
        btn_removerow = new javax.swing.JButton();
        lbl_multiplier = new javax.swing.JLabel();
        lbl_WW = new javax.swing.JLabel();
        display_WW = new javax.swing.JLabel();
        lbl_PT = new javax.swing.JLabel();
        display_PT = new javax.swing.JLabel();
        lbl_QA = new javax.swing.JLabel();
        display_QA = new javax.swing.JLabel();
        panel_myadvisory = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_advisory = new javax.swing.JTable();
        panel_rawscores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_rawscores = new javax.swing.JTable();
        panel_rawscorecalculator = new javax.swing.JPanel();
        lbl_psforww = new javax.swing.JLabel();
        tf_psforww = new javax.swing.JTextField();
        lbl_psforww1 = new javax.swing.JLabel();
        tf_psforww1 = new javax.swing.JTextField();
        lbl_psforww2 = new javax.swing.JLabel();
        tf_psforww2 = new javax.swing.JTextField();
        panel_footer = new javax.swing.JPanel();
        btn_cancel = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_saveandclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Grades");
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel_toppanel.setMinimumSize(new java.awt.Dimension(1000, 700));
        panel_toppanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        panel_toppanel.setLayout(new java.awt.GridBagLayout());

        panel_advisoryselection.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Advisory Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_advisoryselection.setMinimumSize(new java.awt.Dimension(1000, 90));
        panel_advisoryselection.setPreferredSize(new java.awt.Dimension(1000, 90));
        panel_advisoryselection.setLayout(new java.awt.GridBagLayout());

        btn_Edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Edit.setText("Edit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panel_advisoryselection.add(btn_Edit, gridBagConstraints);

        lbl_section.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_section.setText("Section :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_advisoryselection.add(lbl_section, gridBagConstraints);

        combo_section.setEditable(true);
        combo_section.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sunflower" }));
        combo_section.setMinimumSize(new java.awt.Dimension(100, 25));
        combo_section.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panel_advisoryselection.add(combo_section, gridBagConstraints);

        lbl_gradelevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_gradelevel.setText("Grade Level :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_advisoryselection.add(lbl_gradelevel, gridBagConstraints);

        combo_gradelevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_gradelevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo_gradelevel.setMinimumSize(new java.awt.Dimension(100, 25));
        combo_gradelevel.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel_advisoryselection.add(combo_gradelevel, gridBagConstraints);

        lbl_subcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_subcode.setText("Subject Code :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 5);
        panel_advisoryselection.add(lbl_subcode, gridBagConstraints);

        combo_subcode.setEditable(true);
        combo_subcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_subcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "G2English" }));
        combo_subcode.setMinimumSize(new java.awt.Dimension(100, 25));
        combo_subcode.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        panel_advisoryselection.add(combo_subcode, gridBagConstraints);

        lbl_subjectname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_subjectname.setText("Subject Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_advisoryselection.add(lbl_subjectname, gridBagConstraints);

        combo_subjectname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_subjectname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English" }));
        combo_subjectname.setMinimumSize(new java.awt.Dimension(100, 25));
        combo_subjectname.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        panel_advisoryselection.add(combo_subjectname, gridBagConstraints);

        lbl_gradingperiod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_gradingperiod.setText("Grading Period :");
        lbl_gradingperiod.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 5);
        panel_advisoryselection.add(lbl_gradingperiod, gridBagConstraints);

        combo_gradingperiod.setEditable(true);
        combo_gradingperiod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_gradingperiod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th" }));
        combo_gradingperiod.setMinimumSize(new java.awt.Dimension(100, 25));
        combo_gradingperiod.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        panel_advisoryselection.add(combo_gradingperiod, gridBagConstraints);

        btn_addrow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_addrow.setText("Add Row");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        panel_advisoryselection.add(btn_addrow, gridBagConstraints);

        btn_removerow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_removerow.setText("Remove Row");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panel_advisoryselection.add(btn_removerow, gridBagConstraints);

        lbl_multiplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_multiplier.setText("Multipliers --");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panel_advisoryselection.add(lbl_multiplier, gridBagConstraints);

        lbl_WW.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_WW.setText("WW :");
        lbl_WW.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        panel_advisoryselection.add(lbl_WW, gridBagConstraints);

        display_WW.setBackground(new java.awt.Color(187, 187, 187));
        display_WW.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        display_WW.setToolTipText("");
        display_WW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 75, 105)));
        display_WW.setMaximumSize(new java.awt.Dimension(30, 20));
        display_WW.setMinimumSize(new java.awt.Dimension(30, 20));
        display_WW.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        panel_advisoryselection.add(display_WW, gridBagConstraints);

        lbl_PT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_PT.setText("PT :");
        lbl_PT.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panel_advisoryselection.add(lbl_PT, gridBagConstraints);

        display_PT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        display_PT.setToolTipText("");
        display_PT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 75, 105)));
        display_PT.setMaximumSize(new java.awt.Dimension(30, 20));
        display_PT.setMinimumSize(new java.awt.Dimension(30, 20));
        display_PT.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        panel_advisoryselection.add(display_PT, gridBagConstraints);

        lbl_QA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_QA.setText("QA :");
        lbl_QA.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panel_advisoryselection.add(lbl_QA, gridBagConstraints);

        display_QA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        display_QA.setToolTipText("");
        display_QA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 75, 105)));
        display_QA.setMaximumSize(new java.awt.Dimension(30, 20));
        display_QA.setMinimumSize(new java.awt.Dimension(30, 20));
        display_QA.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        panel_advisoryselection.add(display_QA, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 0.5;
        panel_toppanel.add(panel_advisoryselection, gridBagConstraints);

        panel_myadvisory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Advisory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_myadvisory.setMinimumSize(new java.awt.Dimension(500, 520));
        panel_myadvisory.setPreferredSize(new java.awt.Dimension(500, 520));
        panel_myadvisory.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(485, 495));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(485, 495));

        table_advisory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_advisory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Transmuted Grade", "Total WS(Initial Grade)", "Total WS (WW)", "Total WS(PT)", "QA"
            }
        ));
        table_advisory.setRowHeight(20);
        jScrollPane1.setViewportView(table_advisory);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_myadvisory.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        panel_toppanel.add(panel_myadvisory, gridBagConstraints);

        panel_rawscores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Raw Scores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_rawscores.setMinimumSize(new java.awt.Dimension(500, 520));
        panel_rawscores.setPreferredSize(new java.awt.Dimension(500, 520));
        panel_rawscores.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(490, 440));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(485, 440));

        table_rawscores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Component", "Raw Score", "Highest Score", "Percentage Score"
            }
        ));
        table_rawscores.setRowHeight(20);
        jScrollPane2.setViewportView(table_rawscores);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panel_rawscores.add(jScrollPane2, gridBagConstraints);

        panel_rawscorecalculator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        panel_rawscorecalculator.setMinimumSize(new java.awt.Dimension(485, 50));
        panel_rawscorecalculator.setPreferredSize(new java.awt.Dimension(485, 50));
        panel_rawscorecalculator.setLayout(new java.awt.GridBagLayout());

        lbl_psforww.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_psforww.setText("Total PS for WW :");
        lbl_psforww.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_rawscorecalculator.add(lbl_psforww, gridBagConstraints);

        tf_psforww.setEditable(false);
        tf_psforww.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_psforww.setMinimumSize(new java.awt.Dimension(50, 25));
        tf_psforww.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panel_rawscorecalculator.add(tf_psforww, gridBagConstraints);

        lbl_psforww1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_psforww1.setText("Total PS for PT :");
        lbl_psforww1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panel_rawscorecalculator.add(lbl_psforww1, gridBagConstraints);

        tf_psforww1.setEditable(false);
        tf_psforww1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_psforww1.setMinimumSize(new java.awt.Dimension(50, 25));
        tf_psforww1.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panel_rawscorecalculator.add(tf_psforww1, gridBagConstraints);

        lbl_psforww2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_psforww2.setText("QA :");
        lbl_psforww2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panel_rawscorecalculator.add(lbl_psforww2, gridBagConstraints);

        tf_psforww2.setEditable(false);
        tf_psforww2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_psforww2.setMinimumSize(new java.awt.Dimension(50, 25));
        tf_psforww2.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        panel_rawscorecalculator.add(tf_psforww2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panel_rawscores.add(panel_rawscorecalculator, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        panel_toppanel.add(panel_rawscores, gridBagConstraints);

        panel_footer.setMinimumSize(new java.awt.Dimension(1000, 50));
        panel_footer.setPreferredSize(new java.awt.Dimension(1000, 50));
        panel_footer.setLayout(new java.awt.GridBagLayout());

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.setMaximumSize(new java.awt.Dimension(69, 40));
        btn_cancel.setMinimumSize(new java.awt.Dimension(69, 40));
        btn_cancel.setPreferredSize(new java.awt.Dimension(69, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        panel_footer.add(btn_cancel, gridBagConstraints);

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setMaximumSize(new java.awt.Dimension(60, 40));
        btn_clear.setMinimumSize(new java.awt.Dimension(60, 40));
        btn_clear.setPreferredSize(new java.awt.Dimension(60, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panel_footer.add(btn_clear, gridBagConstraints);

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_save.setText("Save & Close");
        btn_save.setMaximumSize(new java.awt.Dimension(120, 40));
        btn_save.setMinimumSize(new java.awt.Dimension(120, 40));
        btn_save.setPreferredSize(new java.awt.Dimension(120, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panel_footer.add(btn_save, gridBagConstraints);

        btn_saveandclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_saveandclose.setLabel("Save & New");
        btn_saveandclose.setMaximumSize(new java.awt.Dimension(120, 40));
        btn_saveandclose.setMinimumSize(new java.awt.Dimension(120, 40));
        btn_saveandclose.setPreferredSize(new java.awt.Dimension(120, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        panel_footer.add(btn_saveandclose, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        panel_toppanel.add(panel_footer, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panel_toppanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_addrow;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_removerow;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_saveandclose;
    private javax.swing.JComboBox<String> combo_gradelevel;
    private javax.swing.JComboBox<String> combo_gradingperiod;
    private javax.swing.JComboBox<String> combo_section;
    private javax.swing.JComboBox<String> combo_subcode;
    private javax.swing.JComboBox<String> combo_subjectname;
    private javax.swing.JLabel display_PT;
    private javax.swing.JLabel display_QA;
    private javax.swing.JLabel display_WW;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_PT;
    private javax.swing.JLabel lbl_QA;
    private javax.swing.JLabel lbl_WW;
    private javax.swing.JLabel lbl_gradelevel;
    private javax.swing.JLabel lbl_gradingperiod;
    private javax.swing.JLabel lbl_multiplier;
    private javax.swing.JLabel lbl_psforww;
    private javax.swing.JLabel lbl_psforww1;
    private javax.swing.JLabel lbl_psforww2;
    private javax.swing.JLabel lbl_section;
    private javax.swing.JLabel lbl_subcode;
    private javax.swing.JLabel lbl_subjectname;
    private javax.swing.JPanel panel_advisoryselection;
    private javax.swing.JPanel panel_footer;
    private javax.swing.JPanel panel_myadvisory;
    private javax.swing.JPanel panel_rawscorecalculator;
    private javax.swing.JPanel panel_rawscores;
    private javax.swing.JPanel panel_toppanel;
    private javax.swing.JTable table_advisory;
    private javax.swing.JTable table_rawscores;
    private javax.swing.JTextField tf_psforww;
    private javax.swing.JTextField tf_psforww1;
    private javax.swing.JTextField tf_psforww2;
    // End of variables declaration//GEN-END:variables
}
