/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moph_ui;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class dialog_feecreate extends javax.swing.JDialog {

    /**
     * Creates new form dialog_feecreate
     */
    public dialog_feecreate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_toppanel = new javax.swing.JPanel();
        panel_roomdetails = new javax.swing.JPanel();
        lbl_roomname = new javax.swing.JLabel();
        tf_roomname = new javax.swing.JTextField();
        lbl_roombldg = new javax.swing.JLabel();
        lbl_roomstatus = new javax.swing.JLabel();
        combo_status = new javax.swing.JComboBox<>();
        lbl_capacity = new javax.swing.JLabel();
        tf_capacity = new javax.swing.JTextField();
        combo_status1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        panel_roomnotes = new javax.swing.JPanel();
        check_kinder = new javax.swing.JCheckBox();
        check_Grade1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        check_Grade2 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        check_Grade3 = new javax.swing.JCheckBox();
        jTextField4 = new javax.swing.JTextField();
        check_Grade4 = new javax.swing.JCheckBox();
        jTextField5 = new javax.swing.JTextField();
        check_Grade5 = new javax.swing.JCheckBox();
        jTextField6 = new javax.swing.JTextField();
        check_Grade6 = new javax.swing.JCheckBox();
        jTextField7 = new javax.swing.JTextField();
        check_Grade7 = new javax.swing.JCheckBox();
        jTextField8 = new javax.swing.JTextField();
        check_Grade8 = new javax.swing.JCheckBox();
        jTextField9 = new javax.swing.JTextField();
        check_Grade9 = new javax.swing.JCheckBox();
        jTextField10 = new javax.swing.JTextField();
        check_Grade10 = new javax.swing.JCheckBox();
        jTextField11 = new javax.swing.JTextField();
        panel_footer = new javax.swing.JPanel();
        btn_cancel = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_savennew = new javax.swing.JButton();
        panel_roomnotes1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Fee");
        setMinimumSize(new java.awt.Dimension(555, 520));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(555, 520));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel_toppanel.setMinimumSize(new java.awt.Dimension(555, 520));
        panel_toppanel.setPreferredSize(new java.awt.Dimension(555, 520));
        panel_toppanel.setLayout(new java.awt.GridBagLayout());

        panel_roomdetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_roomdetails.setMinimumSize(new java.awt.Dimension(550, 100));
        panel_roomdetails.setPreferredSize(new java.awt.Dimension(550, 100));
        panel_roomdetails.setLayout(new java.awt.GridBagLayout());

        lbl_roomname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_roomname.setText("Fee Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 0);
        panel_roomdetails.add(lbl_roomname, gridBagConstraints);

        tf_roomname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_roomname.setMinimumSize(new java.awt.Dimension(150, 25));
        tf_roomname.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 0);
        panel_roomdetails.add(tf_roomname, gridBagConstraints);

        lbl_roombldg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_roombldg.setText("Category :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 10, 0);
        panel_roomdetails.add(lbl_roombldg, gridBagConstraints);

        lbl_roomstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_roomstatus.setText("Active :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panel_roomdetails.add(lbl_roomstatus, gridBagConstraints);

        combo_status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_roomdetails.add(combo_status, gridBagConstraints);

        lbl_capacity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_capacity.setText("Amount :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panel_roomdetails.add(lbl_capacity, gridBagConstraints);

        tf_capacity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_capacity.setMinimumSize(new java.awt.Dimension(50, 25));
        tf_capacity.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        panel_roomdetails.add(tf_capacity, gridBagConstraints);

        combo_status1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_status1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic" }));
        combo_status1.setMinimumSize(new java.awt.Dimension(150, 25));
        combo_status1.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        panel_roomdetails.add(combo_status1, gridBagConstraints);

        jButton1.setText("Apply to All");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 32));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 32));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel_roomdetails.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 3);
        panel_toppanel.add(panel_roomdetails, gridBagConstraints);

        panel_roomnotes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grade Levels", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_roomnotes.setMinimumSize(new java.awt.Dimension(550, 170));
        panel_roomnotes.setPreferredSize(new java.awt.Dimension(550, 170));
        panel_roomnotes.setLayout(new java.awt.GridBagLayout());

        check_kinder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_kinder.setText("Kindergarten");
        check_kinder.setMaximumSize(new java.awt.Dimension(98, 25));
        check_kinder.setMinimumSize(new java.awt.Dimension(98, 25));
        check_kinder.setPreferredSize(new java.awt.Dimension(98, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panel_roomnotes.add(check_kinder, gridBagConstraints);

        check_Grade1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade1.setText("Grade 1");
        check_Grade1.setMaximumSize(new java.awt.Dimension(71, 25));
        check_Grade1.setMinimumSize(new java.awt.Dimension(71, 25));
        check_Grade1.setPreferredSize(new java.awt.Dimension(71, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panel_roomnotes.add(check_Grade1, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_roomnotes.add(jTextField1, gridBagConstraints);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField2.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_roomnotes.add(jTextField2, gridBagConstraints);

        check_Grade2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade2.setText("Grade 4");
        check_Grade2.setMaximumSize(new java.awt.Dimension(71, 25));
        check_Grade2.setMinimumSize(new java.awt.Dimension(71, 25));
        check_Grade2.setPreferredSize(new java.awt.Dimension(71, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 5, 0);
        panel_roomnotes.add(check_Grade2, gridBagConstraints);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField3.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_roomnotes.add(jTextField3, gridBagConstraints);

        check_Grade3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade3.setText("Grade 6");
        check_Grade3.setMaximumSize(new java.awt.Dimension(71, 25));
        check_Grade3.setMinimumSize(new java.awt.Dimension(71, 25));
        check_Grade3.setPreferredSize(new java.awt.Dimension(71, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 5, 0);
        panel_roomnotes.add(check_Grade3, gridBagConstraints);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField4.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_roomnotes.add(jTextField4, gridBagConstraints);

        check_Grade4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade4.setText("Grade 8");
        check_Grade4.setMaximumSize(new java.awt.Dimension(71, 25));
        check_Grade4.setMinimumSize(new java.awt.Dimension(71, 25));
        check_Grade4.setPreferredSize(new java.awt.Dimension(71, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 5, 0);
        panel_roomnotes.add(check_Grade4, gridBagConstraints);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField5.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 20);
        panel_roomnotes.add(jTextField5, gridBagConstraints);

        check_Grade5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade5.setText("Grade 2");
        check_Grade5.setToolTipText("");
        check_Grade5.setMaximumSize(new java.awt.Dimension(71, 25));
        check_Grade5.setMinimumSize(new java.awt.Dimension(71, 25));
        check_Grade5.setPreferredSize(new java.awt.Dimension(71, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panel_roomnotes.add(check_Grade5, gridBagConstraints);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField6.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField6.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_roomnotes.add(jTextField6, gridBagConstraints);

        check_Grade6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade6.setText("Grade 5");
        check_Grade6.setMaximumSize(new java.awt.Dimension(71, 25));
        check_Grade6.setMinimumSize(new java.awt.Dimension(71, 25));
        check_Grade6.setPreferredSize(new java.awt.Dimension(71, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 5, 0);
        panel_roomnotes.add(check_Grade6, gridBagConstraints);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField7.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField7.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_roomnotes.add(jTextField7, gridBagConstraints);

        check_Grade7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade7.setText("Grade 7");
        check_Grade7.setMaximumSize(new java.awt.Dimension(71, 25));
        check_Grade7.setMinimumSize(new java.awt.Dimension(71, 25));
        check_Grade7.setPreferredSize(new java.awt.Dimension(71, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 5, 0);
        panel_roomnotes.add(check_Grade7, gridBagConstraints);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField8.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField8.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_roomnotes.add(jTextField8, gridBagConstraints);

        check_Grade8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade8.setText("Grade 9");
        check_Grade8.setMaximumSize(new java.awt.Dimension(71, 25));
        check_Grade8.setMinimumSize(new java.awt.Dimension(71, 25));
        check_Grade8.setPreferredSize(new java.awt.Dimension(71, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 5, 0);
        panel_roomnotes.add(check_Grade8, gridBagConstraints);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField9.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField9.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 20);
        panel_roomnotes.add(jTextField9, gridBagConstraints);

        check_Grade9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade9.setText("Grade 3");
        check_Grade9.setActionCommand("Grade 9");
        check_Grade9.setMaximumSize(new java.awt.Dimension(71, 25));
        check_Grade9.setMinimumSize(new java.awt.Dimension(71, 25));
        check_Grade9.setPreferredSize(new java.awt.Dimension(71, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panel_roomnotes.add(check_Grade9, gridBagConstraints);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField10.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField10.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_roomnotes.add(jTextField10, gridBagConstraints);

        check_Grade10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_Grade10.setText("Grade 10");
        check_Grade10.setMaximumSize(new java.awt.Dimension(80, 25));
        check_Grade10.setMinimumSize(new java.awt.Dimension(80, 25));
        check_Grade10.setPreferredSize(new java.awt.Dimension(80, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 5, 0);
        panel_roomnotes.add(check_Grade10, gridBagConstraints);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField11.setMinimumSize(new java.awt.Dimension(50, 25));
        jTextField11.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 20);
        panel_roomnotes.add(jTextField11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        panel_toppanel.add(panel_roomnotes, gridBagConstraints);

        panel_footer.setMinimumSize(new java.awt.Dimension(550, 50));
        panel_footer.setPreferredSize(new java.awt.Dimension(550, 50));
        panel_footer.setLayout(new java.awt.GridBagLayout());

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.setMaximumSize(new java.awt.Dimension(69, 40));
        btn_cancel.setMinimumSize(new java.awt.Dimension(69, 40));
        btn_cancel.setPreferredSize(new java.awt.Dimension(69, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        panel_footer.add(btn_cancel, gridBagConstraints);

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setMaximumSize(new java.awt.Dimension(60, 40));
        btn_clear.setMinimumSize(new java.awt.Dimension(60, 40));
        btn_clear.setPreferredSize(new java.awt.Dimension(60, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panel_footer.add(btn_clear, gridBagConstraints);

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_save.setText("Save");
        btn_save.setMaximumSize(new java.awt.Dimension(59, 40));
        btn_save.setMinimumSize(new java.awt.Dimension(59, 40));
        btn_save.setPreferredSize(new java.awt.Dimension(59, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panel_footer.add(btn_save, gridBagConstraints);

        btn_savennew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_savennew.setText("Save & New");
        btn_savennew.setMaximumSize(new java.awt.Dimension(102, 40));
        btn_savennew.setMinimumSize(new java.awt.Dimension(102, 40));
        btn_savennew.setPreferredSize(new java.awt.Dimension(102, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        panel_footer.add(btn_savennew, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 40, 0);
        panel_toppanel.add(panel_footer, gridBagConstraints);

        panel_roomnotes1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fee Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_roomnotes1.setMinimumSize(new java.awt.Dimension(550, 150));
        panel_roomnotes1.setPreferredSize(new java.awt.Dimension(550, 150));
        panel_roomnotes1.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(535, 120));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(535, 120));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setMinimumSize(new java.awt.Dimension(545, 145));
        jTextArea1.setPreferredSize(new java.awt.Dimension(545, 145));
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_roomnotes1.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        panel_toppanel.add(panel_roomnotes1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(panel_toppanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialog_feecreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialog_feecreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialog_feecreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialog_feecreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialog_feecreate dialog = new dialog_feecreate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_savennew;
    private javax.swing.JCheckBox check_Grade1;
    private javax.swing.JCheckBox check_Grade10;
    private javax.swing.JCheckBox check_Grade2;
    private javax.swing.JCheckBox check_Grade3;
    private javax.swing.JCheckBox check_Grade4;
    private javax.swing.JCheckBox check_Grade5;
    private javax.swing.JCheckBox check_Grade6;
    private javax.swing.JCheckBox check_Grade7;
    private javax.swing.JCheckBox check_Grade8;
    private javax.swing.JCheckBox check_Grade9;
    private javax.swing.JCheckBox check_kinder;
    private javax.swing.JComboBox<String> combo_status;
    private javax.swing.JComboBox<String> combo_status1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl_capacity;
    private javax.swing.JLabel lbl_roombldg;
    private javax.swing.JLabel lbl_roomname;
    private javax.swing.JLabel lbl_roomstatus;
    private javax.swing.JPanel panel_footer;
    private javax.swing.JPanel panel_roomdetails;
    private javax.swing.JPanel panel_roomnotes;
    private javax.swing.JPanel panel_roomnotes1;
    private javax.swing.JPanel panel_toppanel;
    private javax.swing.JTextField tf_capacity;
    private javax.swing.JTextField tf_roomname;
    // End of variables declaration//GEN-END:variables
}
